"""Write packaging/licenses/qt-third-party.txt from the Qt sources.

Qt's libraries contain third-party code (PCRE2, HarfBuzz, libpng, libjpeg,
MD4C, the Unicode data, ...) whose licences ask for their copyright notices
in a binary distribution; the PySide6 wheels ship none of them
(docs/DEPENDENCIES.md §4). Each Qt repository describes that code in
``qt_attribution.json`` files and keeps the licence texts in ``LICENSES/``.
This script lists the components of the Qt modules a ReverbScope bundle ships,
with their copyright lines, and appends every licence text they name, plus
the licence of the ICU libraries that the PySide6 wheels for Linux carry.

Run it again whenever requirements/bundle.lock moves PySide6_Essentials to
another Qt version, with the Qt sources at the matching tag::

    for repo in qtbase qtsvg qtimageformats qtwayland; do
      git clone --depth 1 --branch v6.11.2 https://github.com/qt/$repo.git
    done
    python scripts/qt_third_party_notice.py --qt-version 6.11.2 \\
      --source qtbase --source qtsvg --source qtimageformats --source qtwayland \\
      --icu-license icu4c/LICENSE --icu-version 73.2 \\
      --out packaging/licenses/qt-third-party.txt
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

#: The Qt modules (``QDocModule``) whose libraries or plug-ins a bundle ships:
#: Core, GUI, Widgets, D-Bus, Network, SVG, the image-format plug-ins and the
#: Wayland platform plug-in.
MODULES = {
    "qtcore",
    "qtgui",
    "qtwidgets",
    "qtdbus",
    "qtnetwork",
    "qtsvg",
    "qtimageformats",
    "qtwaylandcompositor",
}
#: Code that never reaches a desktop bundle: build scripts, tests, Android and
#: WebAssembly ports.
NOT_SHIPPED = ("build system", "Android", "WebAssembly", "Qt Test")
_SPDX_ID = re.compile(r"[A-Za-z0-9.+-]+")
_SPDX_WORDS = {"AND", "OR", "WITH"}


def _list(value: Any) -> list[str]:
    if value is None:
        return []
    return [str(item) for item in value] if isinstance(value, list) else [str(value)]


def shipped(entry: dict[str, Any]) -> bool:
    usage = str(entry.get("QtUsage", ""))
    if entry.get("QDocModule") not in MODULES or any(word in usage for word in NOT_SHIPPED):
        return False
    # The Wayland files describe the compositor too, which no bundle contains.
    return entry.get("QDocModule") != "qtwaylandcompositor" or "platform plugin" in usage


def attributions(sources: list[Path]) -> list[dict[str, Any]]:
    found: list[dict[str, Any]] = []
    for source in sources:
        for path in sorted(source.rglob("qt_attribution.json")):
            # Some files carry raw tabs inside strings.
            data = json.loads(path.read_text(encoding="utf-8"), strict=False)
            found += data if isinstance(data, list) else [data]
    unique = {str(entry["Id"]): entry for entry in found if shipped(entry)}
    return sorted(unique.values(), key=lambda entry: str(entry["Name"]).lower())


def licence_ids(expression: str) -> list[str]:
    """The licences of an SPDX expression that ReverbScope relies on.

    Of a choice (``FTL OR GPL-2.0-only``) the first licence is taken, so the
    notice carries the FreeType licence, not the GPL.
    """
    if "(" not in expression:
        expression = expression.split(" OR ", 1)[0]
    return [word for word in _SPDX_ID.findall(expression) if word not in _SPDX_WORDS]


def render(
    qt_version: str, sources: list[Path], icu_license: Path, icu_version: str
) -> tuple[str, list[str]]:
    """The notice text and the licence ids no ``LICENSES/`` folder holds."""
    entries = attributions(sources)
    lines = [
        f"Third-party code inside Qt {qt_version}",
        "=" * 40,
        "",
        "ReverbScope's Desktop Edition ships these Qt libraries and plug-ins from the",
        f"PySide6_Essentials {qt_version} wheel: Qt Core, Qt GUI, Qt Widgets, Qt D-Bus,",
        "Qt Network, Qt OpenGL, Qt SVG, the image-format plug-ins and the platform",
        "plug-ins. Qt itself is used under the LGPL-3.0 (see pyside6.txt). The",
        "components below are part of those libraries; some are used on one",
        "operating system only. The list is generated by",
        "scripts/qt_third_party_notice.py from the qt_attribution.json files of the",
        f"Qt sources at tag v{qt_version}; the licence texts follow it. Where a",
        "component offers a choice of licences, the first one applies.",
        "",
    ]
    wanted: list[str] = []
    for entry in entries:
        version = f" {entry['Version']}" if entry.get("Version") else ""
        lines.append(f"{entry['Name']}{version}")
        lines.append(f"  {' '.join(str(entry.get('QtUsage', '')).split())}")
        lines.append(f"  License: {entry.get('LicenseId', entry.get('License', ''))}")
        lines += [f"  {line}" for line in _list(entry.get("Copyright"))]
        location = entry.get("DownloadLocation") or entry.get("Homepage")
        if location:
            lines.append(f"  Source: {location}")
        lines.append("")
        for licence in licence_ids(str(entry.get("LicenseId", ""))):
            if licence not in wanted:
                wanted.append(licence)
    lines += [
        f"ICU {icu_version}",
        "  The libicu* libraries that the PySide6 wheels for Linux bundle for Qt Core.",
        "  License: Unicode License (ICU), text below",
        f"  Source: https://github.com/unicode-org/icu/releases/tag/release-{icu_version.replace('.', '-')}",
        "",
        "",
        "Licence texts",
        "=" * 40,
    ]
    missing: list[str] = []
    for licence in sorted(wanted):
        text = next(
            (
                path.read_text(encoding="utf-8")
                for source in sources
                if (path := source / "LICENSES" / f"{licence}.txt").is_file()
            ),
            None,
        )
        if text is None:
            missing.append(licence)
            continue
        lines += ["", f"--- {licence} ---", "", text.rstrip()]
    icu_text = icu_license.read_text(encoding="utf-8").rstrip()
    lines += ["", f"--- ICU {icu_version} ---", "", icu_text]
    return "\n".join(lines) + "\n", missing


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("--qt-version", required=True, help="the Qt version, e.g. 6.11.2")
    parser.add_argument(
        "--source", type=Path, action="append", required=True, help="a Qt repository checkout"
    )
    parser.add_argument("--icu-license", type=Path, required=True, help="icu4c/LICENSE")
    parser.add_argument("--icu-version", required=True, help="the bundled ICU, e.g. 73.2")
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)
    text, missing = render(args.qt_version, args.source, args.icu_license, args.icu_version)
    if missing:
        print(f"no licence text in any LICENSES/ folder for: {', '.join(missing)}")
        return 1
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
